### ISSUE TITLE
10.0.0 update

### ISSUE THREAD

**Issue by mjsteinbaugh** [conda-forge/ghostscript-feedstock#26]
### Comment:

Is it safe to merge the 10.0.0 ghostscript update? If so, I have some bandwidth to work on a recipe update.

See related:
https://www.ghostscript.com/releases/index.html

Best,
Mike

**Comment by ocefpaf** [comment]
Yes please! If you send a PR feel free to ping me for a review.

**Comment by tdegeus** [comment]
It would be great if you open a PR!

**Comment by seisman** [comment]
Closed by #28.
