### ISSUE TITLE
ghostscript for Windows

### ISSUE THREAD

**Issue by vinayak-mehta** [conda-forge/ghostscript-feedstock#5]
Issue:
Hey @ocefpaf, why is ghostscript not available for Windows through conda?
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Because we don't have a Windows expert/champion to build it :smile:

If you understand about building packages on Windows please send a PR!

**Comment by vinayak-mehta** [comment]
Haha, I'm not a Windows expert but can look into building ghostscript for Windows. Right off the top, I found this [link on the ghostscript site](https://www.ghostscript.com/doc/9.21/Make.htm) which details how to build a ghostscript executable from source code. Is there any other links you can point me to wrt building on Windows? Thanks!

**Comment by leouieda** [comment]
Fixed in #6

**Comment by vinayak-mehta** [comment]
Thanks!
