### ISSUE TITLE
Version outdated?

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/ghostscript-feedstock#7]
I got the following notification for my package:

Here is a list of all the pending dependencies (and their versions) for this repo. Please double check all dependencies before merging.

| Name | Upstream Version | Current Version |
|:----:|:----------------:|:---------------:|
|ghostscript|9.27|[![Anaconda-Server Badge](https://img.shields.io/conda/vn/conda-forge/ghostscript.svg)](https://anaconda.org/conda-forge/ghostscript)|

I guess this means that this package is trailing behind the upstream release. Have you considered updating?

**Comment by leouieda** [comment]
9.27 is [known to have some bugs](https://github.com/GenericMappingTools/gmt/issues/880) which would break downstream dependencies. It seems that [9.50 is now available](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs950) (strange versioning scheme). Maybe we can try it out.

**Comment by tdegeus** [comment]
Note that the latest ghostscript available on conda simply doesn't work for me (probably related to ghostscript and not to the conda package): I get permission errors which don't occur with 9.27
